version: '3.8'

services:
  proof_api:
    build: .
    ports:
      - "8080:8080"
    tty: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      RUST_BACKTRACE: 1
